language: node_js

node_js:
  - "5.0"

env:
  matrix:
    - NPM_2=true

env:
  global:
  - secure: "j4y6Ch308DXw+8/nZoiWdCUqyKg+L+uOpV0pUjqJQbbsC7ktZFJEk7VhH/yYYq1rDlRsBg6nPzVKeJ3Bah6F2EO7GhfEkASWmsaL6d/NGVN481PGlpTOi59JbWK8NjcEriSMl35YcdfM+yL+sb4CVjGVJoN+wHbUXDtZGKZMwzgDbqXWCXULzpa+P7FIR8Ooq0y0QHLvv1sVtcmU3R1vA9rL/MEhDQHEGWBXjahOPY826NheHy9N1GjYi6KUo1iVwF/0GVsku75myn63BQ3RqmYxIry6nO5UH7Bmizzex04WrQrMXHbIhP2deo1ykMoq2G9MRYKOK1geKYVdj2sX7m5TOHgYRo77oSjJqbJ816L/doJm9yGyIRC96zF3+o+Ac4C3YZzWpmrl1JQDVs+R+I6mb0H0/2fcW9RiYph1mBKVmLoxKdch9DPstMKT/t2IL9Di57eD3xmF8Z/7tIfFPD4s7oEJsZ+HfAU5u2M0UrOhNF4EAUATPxkBWHQsUw9OQivC0QdoWdxOvTaQJNBw0NKpD41jYHLjEIVfGhqF4AhbVBEJiV2tDzA6KhHpJUwfGY4+2odWktpJsclQrM/zoogSWL+KEkN1RVKRznImNzXLWUQ6xTyOvlSOr1HzLQ8BgAB3okvb+mzTOE0rTge3fNJY/kPXWMHJeJXHsfANqIg="

script:
  - npm --version

  - npm install
  - npm run test

cache:
  directories:
    - node_modules

deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy
  on:
    branch: master
